name: Build Android APK

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create keystore from secrets
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${{ github.workspace }}/mobile/my-dashboard.jks

      - name: Run Android build in Docker container
        run: |
          docker run --rm \
            -e KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" \
            -e KEYSTORE_ALIAS="${{ secrets.KEYSTORE_ALIAS }}" \
            -e KEYSTORE_ALIAS_PASSWORD="${{ secrets.KEYSTORE_ALIAS_PASSWORD }}" \
            -v "${{ github.workspace }}/mobile:/app" \
            endykaufman/ionic-capacitor:latest

      - name: List generated APK files
        run: |
          ls -la ${{ github.workspace }}/mobile/android/app/build/outputs/apk/release/

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-release
          path: ${{ github.workspace }}/mobile/android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error